import dynamic from "next/dynamic";
import Head from "next/head";
import { Suspense } from "react";
const AppLoading = dynamic(() => import("@/components/common/AppLoading"));
const ForgotPasswordFlowContainer = dynamic(
  () => import("@/components/forgotPasswod/ForgotPasswordFlowContainer"),
  {
    ssr: false,
  }
);
const Layout = dynamic(() => import("@/components/common/Layout"), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Asset Management - Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<AppLoading />}>
        <Layout>
          <ForgotPasswordFlowContainer />
        </Layout>
      </Suspense>
    </>
  );
}
