import dynamic from "next/dynamic";
import Head from "next/head";
import { Suspense, useEffect } from "react";
import { baseHttpClient } from "../services/utils/utilService";
const AppLoading = dynamic(() => import("@/components/common/AppLoading"));
const LoginComponent = dynamic(() => import("@/components/login/LoginComponent"), { ssr: false });
const Layout = dynamic(() => import("@/components/common/Layout"), { ssr: false });

export default function Home() {
  useEffect(() => {
    const fetchData = async () => {
      const data = await baseHttpClient("https://jsonplaceholder.typicode.com/todos/1", "GET");
      console.log(data, "data");
      return data;
    };
    fetchData();
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<AppLoading />}>
        <Layout>
          <LoginComponent />
        </Layout>
      </Suspense>
    </>
  );
}
